### ISSUE TITLE
Yarn add causes error "expected hoisted manifest"

### ISSUE THREAD

**Issue by manurana** [razorpay/react-native-razorpay#108]
* **Common to Both platforms :-**

  - [x] I have gone through the README (https://github.com/razorpay/react-native-razorpay)
  - [x] I have searched for a similar issue (https://github.com/razorpay/react-native-razorpay/issues)
  - [x] I am using the latest version of our framework (https://github.com/razorpay/react-native-razorpay/releases)
  - [ ] I have cleaned my project.

* **Specific to iOS Users :-**

  - [ ] I have modified the module map as specified in the readme (https://github.com/razorpay/react-native-razorpay)
  - [ ] I have deleted the contents of the derived data folder and rebuild it.

I am trying to add this package to my project. I used the command 
`yarn add react-native-razorpay`

I am getting a yarn error on this.
Here is the install log 

```
⟩ yarn add react-native-razorpay
yarn add v1.9.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @mapbox/react-native-mapbox-gl@6.1.2-beta2" has unmet peer dependency "prop-types@>=15.5.8".
warning " > react-native-firebase@4.2.0" has unmet peer dependency "fbjs@*".
warning " > react-native-looped-carousel@0.1.10" has incorrect peer dependency "react-native@^0.54.0".
warning " > react-native-maps@0.21.0" has incorrect peer dependency "react-native@^0.51 || ^0.52 || ^0.53 || ^0.54".
warning " > react-native-maps@0.21.0" has unmet peer dependency "prop-types@^15.0 || ^16.0".
warning "react-navigation > create-react-context@0.2.2" has unmet peer dependency "prop-types@^15.0.0".
warning " > babel-jest@22.4.3" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-0".
warning " > eslint-plugin-prettier@2.6.0" has unmet peer dependency "prettier@>= 0.11.0".
warning "react-native-razorpay > react-native@0.56.1" has incorrect peer dependency "react@16.4.1".
warning "react-native-razorpay > react-native > metro-babel-register > @babel/plugin-proposal-object-rest-spread@7.0.0-beta.47" has unmet peer dependency "@babel/core@7.0.0-beta.47".
warning "react-native-razorpay > react-native > metro-babel-register > @babel/plugin-proposal-class-properties@7.0.0-beta.47"has unmet peer dependency "@babel/core@7.0.0-beta.47".
warning "react-native-razorpay > react-native > metro-babel-register > @babel/plugin-transform-async-to-generator@7.0.0-beta.47" has unmet peer dependency "@babel/core@7.0.0-beta.47".
warning "react-native-razorpay > react-native > metro-babel-register > @babel/plugin-proposal-optional-chaining@7.0.0-beta.47" has unmet peer dependency "@babel/core@7.0.0-beta.47".
warning "react-native-razorpay > react-native > metro-babel-register > @babel/plugin-transform-flow-strip-types@7.0.0-beta.47" has unmet peer dependency "@babel/core@7.0.0-beta.47".
warning "react-native-razorpay > react-native > metro-babel-register > @babel/plugin-transform-modules-commonjs@7.0.0-beta.47" has unmet peer dependency "@babel/core@7.0.0-beta.47".
warning "react-native-razorpay > react-native > metro-babel-register > @babel/register@7.0.0-beta.47" has unmet peer dependency "@babel/core@7.0.0-beta.47".
warning "react-native-razorpay > react-native > metro-babel-register > @babel/plugin-proposal-object-rest-spread > @babel/plugin-syntax-object-rest-spread@7.0.0-beta.47" has unmet peer dependency "@babel/core@7.0.0-beta.47".
warning "react-native-razorpay > react-native > metro-babel-register > @babel/plugin-proposal-class-properties > @babel/plugin-syntax-class-properties@7.0.0-beta.47" has unmet peer dependency "@babel/core@7.0.0-beta.47".
warning "react-native-razorpay > react-native > metro-babel-register > @babel/plugin-proposal-optional-chaining > @babel/plugin-syntax-optional-chaining@7.0.0-beta.47" has unmet peer dependency "@babel/core@7.0.0-beta.47".
warning "react-native-razorpay > react-native > metro-babel-register > @babel/plugin-transform-flow-strip-types > @babel/plugin-syntax-flow@7.0.0-beta.47" has unmet peer dependency "@babel/core@7.0.0-beta.47".
error An unexpected error occurred: "expected hoisted manifest".
info If you think this is a bug, please open a bug report with the information provided in "/Users/manu/developer/@baxi/BaxiApp/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
Here is the log file listing
```
Yarn version:
  1.9.4

Node version:
  8.11.3

Platform:
  darwin x64

Trace:
  Invariant Violation: expected hoisted manifest
      at invariant (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:1745:15)
      at _loop2 (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:86281:9)
      at PackageHoister.init (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:86341:7)
      at PackageLinker.getFlatHoistedTree (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:49539:20)
      at PackageLinker.<anonymous> (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:49550:27)
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:92:30)
      at /usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:110:14
      at new Promise (<anonymous>)
      at new F (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:23624:28)
```

My guess is that this is a yarn error, but is due to the react-native dependency specified in this package.

## IDE Specs
N/A

## Retro Steps

`yarn add react-native-razorpay`

**Comment by manurana** [comment]
Update : I forked this lib, and removed the RN dependency, and it works fine.

**Comment by iThink32** [comment]
closing due to inactivity,reopen if required.
