### ISSUE TITLE
 Unable to start activity ComponentInfo{com.packageName/com.razorpay.CheckoutActivity}

### ISSUE THREAD

**Issue by dverma4u** [razorpay/react-native-razorpay#140]
android application crash giving below logs 

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.packageName/com.razorpay.CheckoutActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by sumedht** [comment]
@dverma4u Which sdk version u r using in the app?
Mean while u can check with Razorpay Sample app from play store to get a better idea.

**Comment by iThink32** [comment]
closing due to inactivity,reopen if required.

**Comment by somangshu** [comment]
@iThink32 i have gotten into the same problem, My razorpay integration works completely fine on the simulator, and the production kernel. Only when i update the app store and the app subsequently the app start to crash. Kindly help as this is very critical and stopping us from making our app live.
