### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:

### ISSUE THREAD

**Issue by kashishgrover** [razorpay/react-native-razorpay#150]
After linking with my new React Native (v0.57.8) project, I'm getting the following error when I run the Metro Bundler:

```

Loading dependency graph...(node:27731) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /Users/kashishgrover/Documents/Codebase/cybertron/starscream/node_modules/react-native/package.json collides with /Users/kashishgrover/Documents/Codebase/cybertron/starscream/node_modules/react-native-razorpay/node_modules/react-native/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/Users/kashishgrover/Documents/Codebase/cybertron/starscream/node_modules/jest-haste-map/build/index.js:462:17)
    at workerReply (/Users/kashishgrover/Documents/Codebase/cybertron/starscream/node_modules/jest-haste-map/build/index.js:512:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:27731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:27731) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exitcode.
(node:27731) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /Users/kashishgrover/Documents/Codebase/cybertron/starscream/node_modules/react-native/package.json collides with /Users/kashishgrover/Documents/Codebase/cybertron/starscream/node_modules/react-native-razorpay/node_modules/react-native/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/Users/kashishgrover/Documents/Codebase/cybertron/starscream/node_modules/jest-haste-map/build/index.js:462:17)
    at workerReply (/Users/kashishgrover/Documents/Codebase/cybertron/starscream/node_modules/jest-haste-map/build/index.js:512:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:27731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by iThink32** [comment]
@kashishgrover ok so the issue here is that there is a node_modules folder inside react-native razorpay.Just delete it or blacklist it.

**Comment by iThink32** [comment]
@kashishgrover  yes agreed that is why in our latest package we have moved it to devDependencies instead of dependancies.

**Comment by iThink32** [comment]
closing due to inactivity,reopen if required.
