### ISSUE TITLE
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.razorTest.razorpayMe/host.exp.exponent.MainActivity}: java.lang.IllegalArgumentException: unexpected url

### ISSUE THREAD

**Issue by devautor** [razorpay/react-native-razorpay#153]
I have an expo app ejected to use ExpoKit, where I have followed the steps listed here to get react-native-razorpay integrated. My app when run with Android Studio throws the following error stack:
```
01/29 23:15:30: Launching app
$ adb shell am start -n "com.razorTest.razorpayMe/host.exp.exponent.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Waiting for process to come online
Waiting for process to come online
Connected to process 15077 on device xiaomi-poco_f1-c169faef
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/AsyncCondition: Could not find listener for key: openOptimisticExperienceActivity
    Could not find listener for key: openExperienceActivity
D/SoLoader: init exiting
I/Timeline: Timeline: Activity_launch_request time:178999653
E/AppLoader: Error fetching cached manifest, falling back to default timeout: Could not load manifest. Are you sure this experience has been published?
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.razorTest.razorpayMe, PID: 15077
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.razorTest.razorpayMe/host.exp.exponent.MainActivity}: java.lang.IllegalArgumentException: unexpected url: http:
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.IllegalArgumentException: unexpected url: http:
        at expolib_v1.okhttp3.Request$Builder.url(Request.java:142)
        at host.exp.exponent.kernel.ExponentUrls.addExponentHeadersToUrl(ExponentUrls.java:45)
        at host.exp.exponent.kernel.ExponentUrls.addExponentHeadersToManifestUrl(ExponentUrls.java:57)
        at host.exp.exponent.ExponentManifest.fetchManifest(ExponentManifest.java:212)
        at host.exp.exponent.ExponentManifest.fetchManifest(ExponentManifest.java:196)
        at host.exp.exponent.AppLoader.fetchRemoteManifest(AppLoader.java:193)
        at host.exp.exponent.AppLoader.startTimerAndFetchRemoteManifest(AppLoader.java:189)
        at host.exp.exponent.AppLoader.startTimerAndFetchRemoteManifest(AppLoader.java:183)
        at host.exp.exponent.AppLoader.access$800(AppLoader.java:20)
        at host.exp.exponent.AppLoader$3.onError(AppLoader.java:160)
        at host.exp.exponent.ExponentManifest.fetchCachedManifest(ExponentManifest.java:288)
        at host.exp.exponent.AppLoader.start(AppLoader.java:91)
        at host.exp.exponent.experience.DetachActivity.onCreate(DetachActivity.java:96)
        at android.app.Activity.performCreate(Activity.java:7210)
        at android.app.Activity.performCreate(Activity.java:7201)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6806) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
E/MQSEventManagerDelegate: failed to get MQSService.
I/Process: Sending signal. PID: 15077 SIG: 9
Application terminated.
```

Also, on running the example project using `react-native run-android`, I am getting this:
`ERROR: Could not find method implementation() for arguments [com.facebook.react:react-native:0.20.+] on project ':react-native-razorpay'.`

I do not have any prior experience with native programming to make any calculated guesses, and couldn't find a direction after a few hours of googling and trying.  Please help!

**Comment by sumedht** [comment]
@devautor Looks like this issue is because of some changes needs to be done in build.gradle file. Will check it at our end and update you soon.

**Comment by devautor** [comment]
Happy that stuffs need to be done on your end :) Will be waiting for the update, thanks!

**Comment by iThink32** [comment]
@devautor we do not support expo , please go through the readme.

**Comment by devautor** [comment]
Hi @iThink32 I did read the manual, I have this app `ejected` from expo. Do you suggest to eject to native, and not to "expokit"? (There are tge two options: eject to keep using expo sdk (i.e. expokit (did this)), and eject completely to native.

**Comment by iThink32** [comment]
@devautor as far as I know expo doesn't support native modules so using expo-kit will also not support them , you have to make sure that your app is using `native` react-native frameworks to be able to use our package as it is a wrapper around an android/ios framework.

**Comment by devautor** [comment]
@iThink32 Really sorry for the trouble, but I guess I really need some direction here. I am following this [expo doc](https://docs.expo.io/versions/latest/expokit/expokit/) where it says this:
"Android
Many libraries in the React Native ecosystem include instructions to run react-native link. These are supported with ExpoKit for Android."

Also, was trying to understand [this](https://stackoverflow.com/questions/49328412/difference-between-expokit-and-react-native-project).

**Comment by iThink32** [comment]
@devautor native modules are not supported on expo

https://docs.expo.io/versions/latest/introduction/faq/

pls read about native modules.

**Comment by iThink32** [comment]
@devautor 
By native I mean native - iOS and native-android modules and not react-native modules.
Our package uses a native-iOS / Android framework as react-native supports it but not expo.

**Comment by devautor** [comment]
Understood @iThink32, thanks. I will try with a "full eject" to platform native code, and will let you guys know :)

**Comment by iThink32** [comment]
closing due to inactivity.

**Comment by JulianKingman** [comment]
FWIW ejected expo _does_ support linking native libraries, that's what ejecting does.

**Comment by sayedIsaq** [comment]
I also got this issue did you find any solution
