### ISSUE TITLE
Unable to link library in fresh project

### ISSUE THREAD

**Issue by atulmy** [razorpay/react-native-razorpay#156]
```
> react-native link react-native-razorpay    

rnpm-install info Linking react-native-razorpay ios dependency 
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'buildConfigurationList' of undefined 

Cannot read property 'buildConfigurationList' of undefined

TypeError: Cannot read property 'buildConfigurationList' of undefined
    at mobile/node_modules/react-native/local-cli/link/ios/getTargets.js:18:68
    at Array.map (<anonymous>)
    at getTargets (mobile/node_modules/react-native/local-cli/link/ios/getTargets.js:16:18)
    at registerNativeModuleIOS (mobile/node_modules/react-native/local-cli/link/ios/registerNativeModule.js:53:3)
    at Object.registerNativeModule [as register] (mobile/node_modules/react-native/local-cli/link/ios/common/registerNativeModule.js:22:5)
    at Object.keys.forEach.platform (mobile/node_modules/react-native/local-cli/link/link.js:74:16)
    at Array.forEach (<anonymous>)
    at linkDependency (mobile/node_modules/react-native/local-cli/link/link.js:44:32)
```

**Comment by iThink32** [comment]
@atulmy a few clients have faced a similar issue with the react-native link command , please follow the manual linking process mentioned here
https://facebook.github.io/react-native/docs/linking-libraries-ios

**Comment by sillysachin** [comment]
Neither manual steps work nor the automatic steps work! 
https://medium.com/@sachin.r.r/using-razorpay-in-react-native-sample-3dea020de6a5
