### ISSUE TITLE
Razorpay is getting crash

### ISSUE THREAD

**Issue by koutily** [razorpay/react-native-razorpay#175]
The APK build and simulator running successful.  But the application getting crash in real device

**Comment by koutily** [comment]
this is the error 

com.facebook.react.bridge.NoSuchKeyException: lineNumber
	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:120)
	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:124)
	at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:178)
	at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:742)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:157)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:818)

**Comment by pronav** [comment]
Can you let us know device as well as plugin version?

**Comment by koutily** [comment]
Device Is MI A2
Versions:  
    "axios": "^0.18.0",
    "react": "16.6.3",
    "react-native": "0.58.6",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-image-picker": "^0.28.1",
    "react-native-razorpay": "^2.1.0",
    "react-native-svg": "^9.3.7",
    "react-navigation": "^3.6.1",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"

**Comment by koutily** [comment]
We have resolved the issue it is due to some functionality issue.

**Comment by yogeshchoudhary147** [comment]
@koutily How did you solve it? I started experiencing this crash from last 1 week.

**Comment by prateekchachra** [comment]
+1. Crash is happening here too.

**Comment by reetika-2** [comment]
App Crash is happening on real android phone.

**Comment by reetika-2** [comment]
How to solve it?
version: "react-native-razorpay": "^2.1.30",
"expokit": "^35.0.1",
 "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",

device is : Samsung On5 pro
