### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION: java.lang.RuntimeException: Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by Yavicarlos** [razorpay/react-native-razorpay#211]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.advancedcalculator, PID: 19468
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.advancedcalculator/com.example.advancedcalculator.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2974)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
        at com.example.advancedcalculator.MainActivity.onCreate(MainActivity.java:71)
        at android.app.Activity.performCreate(Activity.java:7258)
        at android.app.Activity.performCreate(Activity.java:7249)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7000) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by sumedht** [comment]
@Yavicarlos Doesn't look like from crash that it is Razorpay issue

**Comment by DilipCoder** [comment]
![WhatsApp Image 2020-08-18 at 3 48 56 PM](https://user-images.githubusercontent.com/25370616/90501885-a937a280-e16a-11ea-91a0-f2a81eecb111.jpeg)
it's working fine in debug mode but in build in crashed. the crash report is in the screenshot.

info
1 rn version: 0.62.2
2. react-native-razor-pay versin: 2.2.0

although the error is the same for another version like 2.13.5 too.

**Comment by sumedht** [comment]
@DilipCoder Have u added proguard rules?

**Comment by vivekshindhe** [comment]
losing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
