### ISSUE TITLE
 Task :app:processDebugManifest FAILED   i got this error my react native v6.3

### ISSUE THREAD

**Issue by anujec722** [razorpay/react-native-razorpay#289]
See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
364 actionable tasks: 4 executed, 360 up-to-date
C:\Users\ss\simi\android\app\src\debug\AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [com.razorpay:checkout:1.6.3] C:\Users\ss\.gradle\caches\transforms-2\files-2.1\fe7c39f37fed113d582c901e55ce7d35\checkout-1.6.3\AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 19,
                or use tools:overrideLibrary="com.razorpay" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [com.razorpay:checkout:1.6.3] C:\Users\ss\.gradle\caches\transforms-2\files-2.1\fe7c39f37fed113d582c901e55ce7d35\checkout-1.6.3\AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 19,
                or use tools:overrideLibrary="com.razorpay" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
C:\Users\ss\simi\android\app\src\debug\AndroidManifest.xml Error:

**Comment by vivekshindhe** [comment]
Hey @anujec722 Thanks for reaching out to us. So, the deal here is that the SDK uses minVersion of 19. Because 16 is just a bit too outdated right now. Here's how you can change the minSdkVersion on your project, 

> root_project_folder/android/build.gradle and change minSdkVersion to 19. 

Let me know if this resolves the issue for you. 

Thanks

**Comment by veermetri05** [comment]
I also faced this issue and changing the minSdkVersion in android/build.gradle solved the problem it is working fine now.
Thanks for your response @vivekshindhe

**Comment by Daniyalzakir321** [comment]
buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        **minSdkVersion = 21**                  // <--now use this
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

![image](https://user-images.githubusercontent.com/41327126/103152259-31dad680-473b-11eb-9336-290ea798eab9.png)

**Comment by shasank27** [comment]
Where should I change?
There's no option to do it
`buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

> 

> `

**Comment by vivekshindhe** [comment]
@shasank27 You are checking the wrong build.gradle file. There are two, build.gradle(:project_name) & build.gradle(:app). build.gradle(:app) is where you'll find the option to change. It'll be inside **defaultConfig** tag in **android**

**Comment by shasank27** [comment]
Thank you. @vivekshindhe 
It's fixed now

**Comment by mharis17** [comment]
> **INSIDE /android/build.gradle**
> 
> buildscript {
> ext {
> buildToolsVersion = "29.0.2"
> **minSdkVersion = 21** // <--now use this
> compileSdkVersion = 29
> targetSdkVersion = 29
> }
> }
> 
> ![image](https://user-images.githubusercontent.com/41327126/103152259-31dad680-473b-11eb-9336-290ea798eab9.png)

 buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
used this combination ,got the same error..

**Comment by vivekshindhe** [comment]
minSdkVersion should be 21

**Comment by ankit1456** [comment]
![Uploading IMG-20211217-WA0001.jpeg…]()

**Comment by ankit1456** [comment]
Any solution for this issue?

**Comment by ankit1456** [comment]
![IMG-20211217-WA0001](https://user-images.githubusercontent.com/62655089/146472617-019760b0-5ffb-41c1-b4a4-fe651ca60ca8.jpeg)
Any fix for this issue? please help me

**Comment by akib-shaikh-coder** [comment]
@ankit1456 if u installed already old build from android studio or anywhere...try after removing it

**Comment by specter1997** [comment]
> ![IMG-20211217-WA0001](https://user-images.githubusercontent.com/62655089/146472617-019760b0-5ffb-41c1-b4a4-fe651ca60ca8.jpeg) Any fix for this issue? please help me

I have the same problem. If there is any solution plz??

**Comment by homosape** [comment]
Same problem here
```
> Task :app:processDebugMainManifest FAILED
11 actionable tasks: 2 executed, 9 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @36db065a

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @36db065a

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

    at makeError (/Users/ika/Desktop/test/node_modules/execa/index.js:174:9)
    at /Users/ika/Desktop/test/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (/Users/ika/Desktop/test/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/ika/Desktop/test/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
```

**Comment by Luttennet** [comment]
@homosape did you solved it? i have the same issue

**Comment by homosape** [comment]
@Luttennet  yes check this -> [https://github.com/react-native-community/cli/issues/1574](url)

**Comment by Luttennet** [comment]
@homosape thanks mate, helped me too! I didn't even notice it changed to 18 (I think android studio downloaded it auto sadly) thank you

**Comment by Lyle-Rogers** [comment]
This is the main error I had: > Task :app:processDebugMainManifest FAILED

I fixed it by adding android:exported="true" to the \android\app\src\main\AndroidManifest.xml files activity section. For example:
`<activity
  android:name=".MainActivity"
  android:exported="true"> // <- add it here. ! . !
  <intent-filter>
      <action android:name="android.intent.action.MAIN" />
      <category android:name="android.intent.category.LAUNCHER" />
  </intent-filter>
</activity>`
and just after cd .\android\ & ./gradlew clean!

**Comment by mehraj43** [comment]
![image](https://user-images.githubusercontent.com/53511710/193198341-0421dbda-4322-4146-8838-1ecf18c6c61e.png)

**Comment by mehraj43** [comment]
help me guyz stuck with this issue for 2 days couldn't find any solution

**Comment by mehraj43** [comment]
i uninstalled admob even then same issue

**Comment by vivekshindhe** [comment]
@mehraj43 this doesn't have anything to do with the react-native-razorpay package. But, the activity EmptyFloatingActivity needs to have android:exported to be set to true or false in the AndroidManifest.xml. The location of the file is given in the error message you posted above. Adding that should solve it for you

**Comment by mehraj43** [comment]
there is no activity in my file such as EmptyFloatingActivity can u tell me specifically

**Comment by mehraj43** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.supersports">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">

      <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
   	  <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true"
        android:screenOrientation="portrait" 
         >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>

      
    <activity android:name="com.facebook.FacebookActivity"
        android:configChanges=
                "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
        android:label="@string/app_name" />
    <activity
        android:name="com.facebook.CustomTabActivity"
        android:exported="true">
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="@string/fb_login_protocol_scheme" />
        </intent-filter>
    </activity>


    </application>
</manifest>


this manifest of main location

**Comment by mehraj43** [comment]
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <application
        android:usesCleartextTraffic="true"
        tools:targetApi="28"
        tools:ignore="GoogleAppIndexingWarning">
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" android:exported="false" />
    </application>
</manifest>
 
this is of debug location

**Comment by mehraj43** [comment]
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.google.android.ads.consent" >

    <uses-sdk
        android:minSdkVersion="14"
        android:targetSdkVersion="26" />

</manifest>

**Comment by mehraj43** [comment]
> ```
> <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
> 
> <application
>     android:usesCleartextTraffic="true"
>     tools:targetApi="28"
>     tools:ignore="GoogleAppIndexingWarning">
>     <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" android:exported="false" />
> </application>
> ```
> 
> this is of debug location

the error is of this location how do i add the activity

**Comment by vivekshindhe** [comment]
@mehraj43 
`  <activity
            android:name="androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity"
            android:exported="false" />
        <activity
            android:name="androidx.test.core.app.InstrumentationActivityInvoker$EmptyActivity"
            android:exported="false" />
        <activity
            android:name="androidx.test.core.app.InstrumentationActivityInvoker$EmptyFloatingActivity"
            android:exported="false" />`

add these lines to your Application's AndroidManifest.xml file.

**Comment by mehraj43** [comment]
thanks already did its resolve i think now was able to do bcoz of ur previoys reply thanks man

**Comment by mehraj43** [comment]
![image](https://user-images.githubusercontent.com/53511710/193204145-ea9edabc-e828-49e9-b843-aa6289abbb02.png)


a new error occured now

**Comment by vivekshindhe** [comment]
The error is in react-native-fbsdk-next. They would be able to help you out there

**Comment by mehraj43** [comment]
> The error is in react-native-fbsdk-next. They would be able to help you out there

ok thanks

**Comment by MostafaHamdy3** [comment]
How can I solve this issue, plz 
It occurs when I'm trying to run a React native project.
I'm trying to solve this issue 2days ago.

![image](https://github.com/razorpay/react-native-razorpay/assets/73959716/32379751-fe97-4a55-9478-8cba79de9cc0)

**Comment by MrGautamojha** [comment]
I am getting same error 

Using  ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
    }
    
<img width="1120" alt="Screenshot 2024-04-26 at 2 23 01 PM" src="https://github.com/razorpay/react-native-razorpay/assets/47115026/12c793d5-9683-44fa-89eb-5df4d0e1cb2f">

**Comment by Yash0922** [comment]
![image](https://github.com/user-attachments/assets/2ec0f88f-f2dd-49b1-812b-3b7d5d8a86b7)

i git this error

**Comment by anujec722** [comment]
Ok I will update this

**Comment by Abhishekc2** [comment]
> Task :app:processDebugMainManifest FAILED
[androidx.versionedparcelable:versionedparcelable:1.1.1] gradle\caches\8.8\transforms\0341223bba1d8894a4a61dfecd31c4fc\transformed\versionedparcelable-1.1.1\AndroidManifest.xml Warning:
        Namespace 'androidx.versionedparcelable' is used in multiple modules and/or libraries: androidx.versionedparcelable:versionedparcelable:1.1.1, com.android.support:versionedparcelable:28.0.0. Please ensure that all modules and libraries have a unique namespace. For more information, See https://developer.android.com/studio/build/configure-app-module#set-namespace

See https://developer.android.com/r/studio-ui/build/manifest-merger for more information about the manifest merger.


Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
198 actionable tasks: 188 executed, 10 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

\android\app\src\debug\AndroidManifest.xml:28:18-86 Error:
        Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.9.0] AndroidManifest.xml:28:18-86
        is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-8:50 to override        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-8:50 to override.


FAILURE: Build failed with an exception.

* What went wrong:
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 49s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
android\app\src\debug\AndroidManifest.xml:28:18-86 Error: Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.9.0] AndroidManifest.xml:28:18-86 is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory). Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-8:50 to override. FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':app:processDebugMainManifest'. > Manifest merger failed with multiple errors, see logs * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 49s.
info Run CLI with --verbose flag for more details.


I am getting this error
