### ISSUE TITLE
React Native - Razorpay intent not closing properly

### ISSUE THREAD

**Issue by dprem06** [razorpay/react-native-razorpay#371]
Hi Team,

I Guess problem between native bridge. Please find my video attached , integrated razor pay  sdk and able to show payment screen , while made transaction success time of razor pay intent close app crashed. even close payment screen intent as well crashed app.

https://user-images.githubusercontent.com/16777140/138551907-fecb29ad-d05d-4782-b412-01c3976122a2.mp4

https://user-images.githubusercontent.com/16777140/138551912-4a237d3f-0b90-4dc3-af6a-6232ab35a57a.mp4

//  **While RazorpayCheckout.open No Crashing but in logs shows error**
2021-10-28 20:14:08.484 7156-7156/com.c2g E/com.razorpay.checkout: GooglePay library not included
2021-10-28 20:14:10.208 1614-7401/? E/ResolverController: No valid NAT64 prefix (100, <unspecified>/0)
2021-10-28 20:14:10.375 7156-7367/com.c2g E/cr_SBApiBridge: Failed to init handler: Attempt to invoke virtual method 'java.lang.reflect.Constructor java.lang.Class.getDeclaredConstructor(java.lang.Class[])' on a null object reference
2021-10-28 20:14:10.471 1614-7400/? E/ResolverController: No valid NAT64 prefix (100, <unspecified>/0)
2021-10-28 20:14:10.524 7156-7402/com.c2g E/chromium: [ERROR:gl_surface_egl.cc(342)] eglChooseConfig failed with error EGL_SUCCESS
2021-10-28 20:14:10.725 7156-7402/com.c2g E/chromium: [ERROR:gl_surface_egl.cc(342)] eglChooseConfig failed with error EGL_SUCCESS

// **After entered card details then submit No Crashing but in logs shows error**
2021-10-28 20:15:01.099 7156-7156/com.c2g E/com.razorpay.checkout: Webview JS Error: Uncaught SyntaxError: Invalid or unexpected token
2021-10-28 20:15:01.115 7156-7156/com.c2g E/com.razorpay.checkout: Webview JS Error: Uncaught TypeError: window.getDeviceDetails is not a function

// After pressed Sucess / Failure button throws this exception And Even Crash App

2021-10-28 20:15:17.347 7156-7156/com.c2g E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.c2g, PID: 7156
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;
        at com.razorpay.CheckoutPresenterImpl.cleanUpOnDestroy(CheckoutPresenterImpl.java:704)
        at com.razorpay.a_$P$.onDestroy(BaseCheckoutActivity.java:178)
        at android.app.Activity.performDestroy(Activity.java:8048)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1334)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4926)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4970)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.localbroadcastmanager.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/com.c2g--um5R53bfb4X2C52EJaG2w==/base.apk"],nativeLibraryDirectories=[/data/app/com.c2g--um5R53bfb4X2C52EJaG2w==/lib/x86, /data/app/com.c2g--um5R53bfb4X2C52EJaG2w==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.razorpay.CheckoutPresenterImpl.cleanUpOnDestroy(CheckoutPresenterImpl.java:704) 
        at com.razorpay.a_$P$.onDestroy(BaseCheckoutActivity.java:178) 
        at android.app.Activity.performDestroy(Activity.java:8048) 
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1334) 
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4926) 
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4970) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2021-10-28 20:15:17.448 1867-1959/system_process E/InputDispatcher: channel '23a00d7 com.c2g/com.razorpay.CheckoutActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2021-10-28 20:15:17.481 1867-1959/system_process E/InputDispatcher: channel '489a427 com.c2g/com.c2g.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by vivekshindhe** [comment]
@dprem06  the error was resolved. Please do npm install again and sync the gradle files in android. This should resolve the problem

**Comment by vivekshindhe** [comment]
@dprem06 closing the ticket due to inactivity. Please feel free to reopen, comment, or create another ticket for further assistance. Thank you
