### ISSUE TITLE
Exception in com.razorpay.AutoReadOtpHelper

### ISSUE THREAD

**Issue by punndcoder28** [razorpay/react-native-razorpay#373]
## Description
We have noticed an unhandled crash in our app which uses razorpay for payments. This crash was logged into our crash tracking integration. 
```
Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x200010 pkg=com.myapp.package (has extras) } in com.razorpay.AutoReadOtpHelper@93f4b24
```

This is an exact issue as mentioned in the flutter package [here](https://github.com/razorpay/razorpay-flutter/issues/131)

## Razorpay Package Version :
`^2.2.7`

Complete stack trace can be found here
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x200010 pkg=com.myapp.package (has extras) } in com.razorpay.AutoReadOtpHelper@93f4b24
    at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1581)
    at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:233)
    at android.app.ActivityThread.main(ActivityThread.java:8010)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Comment by punndcoder28** [comment]
Development Team any updates on why this is happening. Our customers are faces crashes due to this exception. Any help would be appreciated a lot

**Comment by vivekshindhe** [comment]
@punndcoder28 Could you send the payload you are sending to the SDK? Also upgrading to version 2.2.8 would be favourable

**Comment by punndcoder28** [comment]
Hi @vivekshindhe I don't think we can get the payload since it is in production that we are facing this issue. I will upgrade the version as well, strange that the tag is not updated on your github repo 😀

**Comment by vivekshindhe** [comment]
@punndcoder28 its fine if it's production but the payload that will be generated is the same right? I don't want personal details like prefill.contact and all. Just the payload you are sending. Even the one you are using in debug will work

**Comment by devanshsadhotra25** [comment]
I am using 2.2.8 and it's there whenever there is a UPI payment success, or EMI payment success
