### ISSUE TITLE
App Crashing when using getCardNetworkLength method 

### ISSUE THREAD

**Issue by sudhanshu-housing** [razorpay/react-native-razorpay#476]
## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native Razorpay plugin release to make sure your issue has not already been fixed. 

* **Specific to iOS Users :-**
- [ ] I have tried updating Razorpay pod to the latest version by using 'pod update'.

## Razorpay Package Version :
`react-native-customui@2.2.4`

### What happened:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.has(java.lang.String)' on a null object reference
       at com.razorpay.RazorpayUtils.c(RazorpayUtils.java:269)
       at com.razorpay.BaseRazorpay.getCardNetworkLength(BaseRazorpay.java)
       at com.razorpay.rn.RazorpayModule.getCardNetworkLength(RazorpayModule.java:109)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java)
       at android.os.Looper.loopOnce(Looper.java:222)
       at android.os.Looper.loop(Looper.java:314)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:1012)
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Invoked getCardNetworkLength method from android device(Poco X6 Pro 5G)
2. App crashed

**Comment by vivekshindhe** [comment]
@sudhanshu-housing , Is the issue reproducible on that certain device now as well? Can you please check if there are more crashes of this sort?
