### ISSUE TITLE
 Cannot find module while installing

### ISSUE THREAD

**Issue by mrkhanakia** [razorpay/react-native-razorpay#97]
I am install razorpay and when i run this command i am getting error react-native link react-native-razorpay

```
Amans-MacBook-Pro:uc_reactnative khanakia$ react-native link react-native-razorpay
Scanning folders for symlinks in /Volumes/D/www/js/uc_js/uc_reactnative/node_modules (15ms)
{ Error: Cannot find module '/Volumes/D/www/js/uc_js/uc_reactnative/node_modules/react-native-razorpay/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at getRNPMConfig (/Volumes/D/www/js/uc_js/uc_reactnative/node_modules/react-native/local-cli/core/index.js:53:3)
    at Object.getDependencyConfig (/Volumes/D/www/js/uc_js/uc_reactnative/node_modules/react-native/local-cli/core/index.js:115:18)
    at deps.reduce (/Volumes/D/www/js/uc_js/uc_reactnative/node_modules/react-native/local-cli/link/getDependencyConfig.js:16:24)
    at Array.reduce (<anonymous>)
    at getDependencyConfig (/Volumes/D/www/js/uc_js/uc_reactnative/node_modules/react-native/local-cli/link/getDependencyConfig.js:13:15)
    at Object.link (/Volumes/D/www/js/uc_js/uc_reactnative/node_modules/react-native/local-cli/link/link.js:131:24) code: 'MODULE_NOT_FOUND' }

```

**Comment by iThink32** [comment]
Please follow the manual linking steps in the following link

https://facebook.github.io/react-native/docs/linking-libraries-ios

or refer our integration videos 

https://razorpay.com/docs/ios/integration-videos/

**Comment by iThink32** [comment]
closing due to inactivity.
